<?php
$menus = tve_get_custom_menus();
?>
<div class="row">
	<div class="col-xs-5 group-label grey-text margin-top-5">
		<?php echo __( 'Select Menu', 'thrive-cb' ); ?>
	</div>
	<div class="col-xs-7 tve-select-arrow">
		<select class="tve-select change" data-fn="changeMenu">
			<?php foreach ( $menus as $item ) : ?>
				<option value="<?php echo $item['id'] ?>"><?php echo $item['name'] ?></option>
			<?php endforeach ?>
			<option value="custom"><?php echo __( 'Custom', 'thrive-cb' ); ?></option>
		</select>
	</div>
</div>
