<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 5/7/2018
 * Time: 5:56 PM
 */
?>
<#if(typeof no_item !== 'undefined' && no_item){#>
<div class="list-no-items tcb-text-center"><?php echo __( 'None', 'thrive-cb' ) ?></div>
<#} else {#>
<div class="preview-list-item tcb-relative" data-fn="item_click" data-index="<#=item.index#>">
	<div class="row middle-xs between-xs">
		<div class="col-xs-1"></div>
		<div class="col-xs-7 tcb-relative item-label">
			<div class="preview-list-sort-handle preview-list-sort-handle-no-icon clearfix">
				<span class="col-sep tcb-left"></span>
				<span class="col-sep tcb-left margin-left-5"></span>
			</div>
			<span class="tcb-truncate"><#=item.get('label')#></span>
		</div>
		<div class="col-xs-4 clearfix">
			<div class="tcb-right">
				<span title="<?php esc_attr_e( 'Edit', 'thrive-cb' ) ?>" class="click" data-fn="item_click" data-index="<#=item.index#>">
							<?php tcb_icon( 'edit' ) ?>
				</span>
				<span title="<?php esc_attr_e( 'Remove', 'thrive-cb' ) ?>" class="click" data-fn="item_remove" data-index="<#=item.index#>">
						<?php tcb_icon( 'trash' ) ?>
				</span>
			</div>
		</div>
	</div>
</div>
<#}#>
